version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-docs:
    working_directory: ~/project/docs
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run deploy
workflows:
    build-and-test:
      jobs:
        - deploy-docs
