version: 2.1

orbs:
  node: circleci/node@1.1.6
executors:
  node:
    docker:
      - image: circleci/node:12.16
    working_directory: /tmp/gatsby-plugin-s3

jobs:
  deploy-docs:
    working_directory: ~/project/docs
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/project
      - node/with-cache:
          steps:
            - run: npm ci
            - run:
                command: npm ci
                working_directory: ~/project/docs/.awesome
            - run: npm run build
            - run: npm run deploy
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: 'npm ci --dev'
      - run:
          name: install-example-dependencies
          command: 'cd examples/with-redirects && npm ci --dev && cd ../..'
      - run:
          name: install-dependencies-again
          # Not sure why, but for some reason installing the example dependencies uninstalls some of the main package dependencies
          # Also not sure why, but for some reason installing example dependencies fails if the main package dependencies aren't already installed
          # So we have to install the main package dependencies twice
          command: 'npm ci --dev'
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "examples/with-redirects/package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: ./node_modules/.bin/eslint "src/**.ts" -f junit -o reports/linter-results.xml
      - store_artifacts:
          prefix: tests
          path: "./reports"
      - store_test_results:
          path: "./reports"

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: npm run-script build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test_e2e:
    executor: node
    environment:
      SKIP_BUCKET_CLEANUP: 1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: e2e-tests
          command: npm run-script test:e2e
          environment:
            JEST_JUNIT_OUTPUT: "reports/e2e-test-results.xml"
      - store_artifacts:
          prefix: tests
          path: "./reports"
      - store_test_results:
          path: "./reports"
  notify:
    executor: node
    steps:
      - run:
          command: |
            if [ -z $CIRCLE_PULL_REQUEST ]
            then
              echo "The current build is not a Pull Request. If you intend to open an pull request after this commit, all following commits will be commented"
            else
              # Loop through all Pull Requests
              IFS=','
              for PULL_REQUEST in $CIRCLE_PULL_REQUESTS do
                # Fetch PR Number
                if [[ "$PULL_REQUEST" =~ https://github.com/(.*)/pull/([0-9]+) ]]
                then
                  GITHUB_REPO=${BASH_REMATCH[1]}
                  GITHUB_PR_NUM=${BASH_REMATCH[2]}
                  # Fetch log
                  if [ ! -z $GITTOOLS_LOGPATH ]
                  then
                    PRCOMMENT_LOG="Log:\n$(cat $GITTOOLS_LOGPATH)"
                  fi
                  # Curl Request to post comment to PR
                  ## Currently this seems to only update the top most comment.
                  curl -s -H "Authorization: token ${VCS_TOKEN}" -X POST \
                  -d "{\"body\": \"${GIT_COMMIT_MESSAGE} ${PRCOMMENT_LOG}\"}" \
                  "https://api.github.com/repos/${GITHUB_REPO}/issues/${GITHUB_PR_NUM}/comments"
                else
                  echo "Unable to parse PR URL $PULL_REQUEST"
                fi
              done
              IFS=' '
            fi
      - git-tools/prcomment:
          comment: "Waiting for approval from a project maintainer before running e2e tests. https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID"

workflows:
  deploy-docs:
    jobs:
      - deploy-docs:
          context: gatsby-plugin-s3-docs
          filters:
            branches:
              only: master
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - notify:
          context: gatsby-plugin-s3-github
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - test_e2e:
          context: gatsby-plugin-s3-e2e
          requires:
            - hold